'use strict';
const assert=require('node:assert/strict');
const {KEYWORDS,SPELLS,WANDS,PRESETS,ENEMIES,compile,Battle}=require('./engine.js');
let checks=0;
function test(name,fn){fn();checks++;console.log('PASS',name);}
function near(a,b){assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);}
function steps(b,n){for(let i=0;i<n;i++)b.step();}
function idle(){const b=new Battle({cards:['spark']});b.units.forEach(u=>u.timer=999);return b;}
function hit(b,type,side=0){b.hit({side,type,damage:SPELLS[type].damage},b.units[1-side]);}

test('Ordinary spells are one slot per automatic cast',()=>{const p=compile(PRESETS.burn.cards);assert.equal(p.roots.length,3);assert.ok(p.roots.every(n=>!n.children.length));});
test('Advanced prefix grouping is preserved but optional',()=>{const p=compile(['trigger','double','power','ember','venom','shield']);assert.equal(p.errors.length,0);assert.equal(p.roots.length,2);assert.equal(p.roots[0].children[0].children[0].id,'power');});
test('Reject empty, incomplete, unknown and oversized programs',()=>{for(const c of [[],['trigger'],['double','spark'],['mana'],Array(9).fill('spark')])assert.ok(compile(c).errors.length);assert.throws(()=>new Battle({cards:['trigger']}));});
test('One interval applies at startup, between casts and on wrap',()=>{const b=new Battle({cards:['spark','shield']});b.units[1].timer=999;steps(b,56);assert.equal(b.units[0].stats.casts,0);b.step();assert.equal(b.units[0].stats.casts,1);steps(b,171);const t=b.traces.filter(t=>!t.side);assert.equal(t.length,4);assert.deepEqual(t.map(t=>t.group),[1,2,1,2]);t.forEach((t,i)=>near(t.time,.95*(i+1)));assert.equal('mana' in b.units[0],false);assert.equal('recharge' in b.units[0],false);});
test('Wands trade basic damage for interval, not keyword strength',()=>{const a=new Battle({cards:['ember'],wand:'rapid'}),b=new Battle({cards:['ember'],wand:'deep'});for(const x of [a,b]){x.units[1].timer=999;x.cast(compile(['ember']).roots[0],x.units[0],810,205);}near(a.projectiles[0].damage,2.6);near(b.projectiles[0].damage,5.8);a.step();b.step();assert.equal(a.units[1].burn,4);assert.equal(b.units[1].burn,4);});
test('Burn attaches through shield, first ticks after one second, then decays',()=>{const b=idle(),u=b.units[1];u.shield=50;hit(b,'ember');near(u.shield,46);assert.equal(u.burn,4);steps(b,59);near(u.shield,46);b.step();near(u.shield,42);assert.equal(u.burn,3);near(u.hp,220);steps(b,60);near(u.shield,39);assert.equal(u.burn,2);});
test('Burn bypasses armor but not shield',()=>{const b=idle(),u=b.units[1];u.armor=100;b.addStatus(u,'burn',4);steps(b,60);near(u.hp,216);near(b.units[0].stats.dot,4);});
test('Poison bypasses shield and armor and does not decay',()=>{const b=idle(),u=b.units[1];u.shield=50;u.armor=100;hit(b,'venom');near(u.shield,50);assert.equal(u.poison,2);steps(b,120);near(u.hp,216);near(u.shield,50);assert.equal(u.poison,2);near(b.units[0].stats.dot,4);});
test('Adding stacks does not postpone the next DoT tick',()=>{const b=idle(),u=b.units[1];b.addStatus(u,'burn',4);steps(b,30);b.addStatus(u,'burn',4);near(u.burnAt,1);steps(b,30);near(u.hp,212);assert.equal(u.burn,7);});
test('Expired burn clears its clock and reapplication starts a new one',()=>{const b=idle(),u=b.units[1];b.addStatus(u,'burn',1);steps(b,60);assert.equal(u.burn,0);assert.equal(u.burnAt,0);steps(b,30);b.addStatus(u,'burn',4);near(u.burnAt,2.5);});
test('Status caps prevent unbounded stacks',()=>{const b=idle(),u=b.units[1];for(let i=0;i<30;i++){b.addStatus(u,'burn',4);b.addStatus(u,'poison',2);b.addStatus(u,'shock',2);}assert.equal(u.burn,30);assert.equal(u.poison,30);assert.equal(u.shock,6);});
test('Shock only triggers on subsequent projectile hits, not DoT',()=>{const b=idle(),u=b.units[1];hit(b,'shock');near(u.hp,214);assert.equal(u.shock,2);b.addStatus(u,'poison',1);steps(b,60);assert.equal(u.shock,2);near(u.hp,213);hit(b,'spark');near(u.hp,197);assert.equal(u.shock,1);hit(b,'spark');near(u.hp,181);assert.equal(u.shock,0);});
test('Repeated electric hit consumes old shock before adding fresh stacks',()=>{const b=idle(),u=b.units[1];hit(b,'shock');hit(b,'shock');near(u.hp,202);assert.equal(u.shock,3);});
test('Detonate consumes burn once and applies bonus as shieldable direct damage',()=>{const b=idle(),u=b.units[1];b.addStatus(u,'burn',7);u.shield=12;hit(b,'detonate');near(u.hp,210);near(u.shield,0);assert.equal(u.burn,0);assert.equal(u.burnAt,0);assert.equal(b.units[0].stats.detonations,1);hit(b,'detonate');near(u.hp,202);steps(b,60);near(u.hp,202);});
test('Chill slows the single timer, refreshes duration, never stacks magnitude',()=>{const b=idle(),u=b.units[1];u.timer=10;hit(b,'ice');near(u.slowUntil,2);steps(b,60);near(u.timer,9.3);hit(b,'ice');near(u.slowUntil,3);steps(b,60);near(u.timer,8.6);});
test('Cleanse removes limited DoT stacks and all shock/chill; heals only self',()=>{const b=idle(),u=b.units[0];u.hp=200;b.addStatus(u,'burn',5);b.addStatus(u,'poison',2);b.addStatus(u,'shock',4);u.slowUntil=3;b.cast(compile(['cleanse']).roots[0],u,800,205);near(u.hp,204);assert.equal(u.burn,2);assert.equal(u.poison,0);assert.equal(u.poisonAt,0);assert.equal(u.shock,0);assert.equal(u.slowUntil,0);near(u.burnAt,1);near(b.units[1].hp,220);});
test('Cleanse on the tick boundary resolves before damage',()=>{const b=idle(),u=b.units[0];u.program=compile(['cleanse']);u.cards=['cleanse'];u.timer=1;b.addStatus(u,'poison',2);steps(b,60);assert.equal(u.poison,0);near(u.hp,220);});
test('Shield and healing are capped and always affect caster',()=>{const b=idle(),u=b.units[0];for(let i=0;i<5;i++)b.cast(compile(['shield']).roots[0],u,800,205);assert.equal(u.shield,55);b.cast(compile(['heal']).roots[0],u,800,205);near(u.hp,220);near(b.units[1].shield,0);});
test('Walls block keyword attachment; piercing applies it to opponent',()=>{const b=new Battle({cards:['ember'],wall:true});b.units.forEach(u=>u.timer=999);b.cast(compile(['ember']).roots[0],b.units[0],475,205);b.step();assert.equal(b.units[1].burn,0);near(b.wall.hp,46);b.cast(compile(['pierce','venom']).roots[0],b.units[0],475,205);steps(b,60);assert.equal(b.units[1].poison,2);near(b.wall.hp,46);});
test('Advanced trace preserves lineage and activates children only on impact',()=>{const b=new Battle({cards:PRESETS.payload.cards});b.units[1].timer=999;steps(b,57);const t=b.units[0].lastTrace;assert.deepEqual(Object.keys(t.nodes),['0']);while(!t.triggers.length)b.step();assert.deepEqual(Object.keys(t.nodes),['0','1','2','3']);assert.ok(t.nodes[1]>t.nodes[0]);assert.deepEqual(b.projectiles.filter(p=>p.trace===t).map(p=>p.type).sort(),['detonate','ember']);assert.ok(b.units[0].stats.casts>1);});
test('Nested payload support and keywords are finite, even through a wall',()=>{const b=new Battle({cards:['trigger','double','trigger','venom','cleanse'],wall:true});b.run();assert.ok(b.result);assert.ok(b.units[0].stats.triggers>0);});
test('Simultaneous DoT lethal damage produces a draw',()=>{const b=idle();for(const u of b.units){u.hp=2;b.addStatus(u,'poison',2);}steps(b,60);assert.equal(b.result,'draw');});
test('Overkill is not counted as damage dealt',()=>{const b=idle();b.units[1].hp=3;hit(b,'lance');near(b.units[0].stats.damage,3);near(b.units[1].hp,0);});
test('Healing-only builds terminate at the time limit',()=>{const b=new Battle({cards:['heal']});b.units[1].timer=999;b.run();assert.equal(b.result,'timeout');});
test('Invalid timestep is rejected',()=>{assert.throws(()=>idle().step(1));assert.throws(()=>idle().step(NaN));});
test('Identical configurations produce identical simulation traces',()=>{const c={cards:PRESETS.poison.cards,wall:true,enemy:'alchemist'},a=new Battle(c),b=new Battle(c);a.run();b.run();assert.deepEqual(a,b);});
test('All 168 preset / wand / opponent / wall configurations are finite',()=>{let count=0;for(const p of Object.values(PRESETS))for(const wand of Object.keys(WANDS))for(const enemy of Object.keys(ENEMIES))for(const wall of [false,true]){const b=new Battle({cards:p.cards,wand,enemy,wall});b.run();count++;assert.ok(b.result);for(const u of b.units){assert.ok(Number.isFinite(u.hp)&&u.hp>=0&&u.hp<=220);assert.ok(u.shield>=0&&u.shield<=55);assert.ok(u.burn>=0&&u.burn<=30);assert.ok(u.poison>=0&&u.poison<=30);assert.ok(u.shock>=0&&u.shock<=6);assert.ok(u.stats.dot<=u.stats.damage);}assert.ok(b.projectiles.length<100);}assert.equal(count,168);});
test('Keywords have explicit targets; detonation and cleanse are card actions',()=>{assert.equal(KEYWORDS.detonate,undefined);assert.equal(KEYWORDS.cleanse,undefined);assert.equal(SPELLS.detonate.keyword,undefined);assert.equal(SPELLS.cleanse.keyword,undefined);assert.deepEqual(Object.keys(KEYWORDS).filter(k=>KEYWORDS[k].target==='wand'),['haste','slow','charge']);for(const s of Object.values(SPELLS))if(s.keyword)assert.ok(KEYWORDS[s.keyword]);});
test('Haste changes wand cadence, refreshes, expires and never changes projectile speed',()=>{const b=idle(),u=b.units[0];u.timer=20;b.cast(compile(['surge']).roots[0],u,125,205);near(b.wandRate(u),1.5);steps(b,60);near(u.timer,18.5);b.cast(compile(['surge']).roots[0],u,125,205);near(u.hasteUntil,4);near(b.wandRate(u),1.5);b.cast(compile(['spark']).roots[0],u,125,205);near(Math.hypot(b.projectiles[0].vx,b.projectiles[0].vy),450);steps(b,181);near(b.wandRate(u),1);});
test('Haste and slow coexist multiplicatively on a wand, not on its character',()=>{const b=idle(),u=b.units[0];u.timer=10;b.wandEffect(u,{keyword:'haste',duration:3});hit(b,'ice',1);near(b.wandRate(u),1.05);steps(b,60);near(u.timer,8.95);near(u.hp,215);});
test('Self-charge advances the next cast including loop wrap',()=>{const b=new Battle({cards:['charge','spark']});b.units[1].timer=999;steps(b,57);near(b.units[0].timer,.45);steps(b,27);assert.equal(b.units[0].lastIndex,1);near(b.units[0].lastCastAt,1.4);steps(b,57);near(b.units[0].timer,.45);near(b.units[0].lastCastAt,2.35);});
test('Charge clamps at zero, discards excess and never recursively casts',()=>{const b=new Battle({cards:['double','charge','charge']});b.units[1].timer=999;steps(b,57);const u=b.units[0];near(u.timer,0);assert.equal(u.stats.casts,1);b.step();assert.equal(u.stats.casts,2);near(u.timer,0);steps(b,10);assert.equal(u.stats.casts,12);assert.equal('mana' in u,false);});
test('Charge can advance startup; a fresh battle clears wand effects',()=>{const b=new Battle({cards:['spark']});b.units[1].timer=999;b.wandEffect(b.units[0],{keyword:'charge',amount:10});assert.equal(b.units[0].stats.casts,0);b.step();assert.equal(b.units[0].stats.casts,1);const fresh=new Battle();near(fresh.units[0].timer,.95);near(fresh.units[0].hasteUntil,0);near(fresh.units[0].slowUntil,0);assert.equal(fresh.units[0].lastChargeAt,-99);});
test('Relay hit charges the caster wand, not target, through shield but not wall',()=>{const b=idle(),u=b.units[0],v=b.units[1];u.timer=.8;v.shield=50;hit(b,'relay');near(u.timer,.55);near(v.timer,999);near(v.shield,45);near(v.hp,220);const w=new Battle({cards:['relay'],wall:true});w.units.forEach(u=>u.timer=999);w.cast(compile(['relay']).roots[0],w.units[0],475,205);w.step();assert.equal(w.units[0].lastChargeAt,-99);near(w.wall.hp,45);});
test('Remote payload support still targets its own wand; cleanse preserves haste',()=>{const b=idle(),u=b.units[0];u.timer=.8;b.cast(compile(['charge']).roots[0],u,800,205);near(u.timer,.3);near(b.units[1].timer,999);b.wandEffect(u,{keyword:'haste',duration:3});b.wandEffect(u,{keyword:'slow',duration:2});b.cast(compile(['cleanse']).roots[0],u,800,205);near(u.slowUntil,0);near(u.hasteUntil,3);near(b.wandRate(u),1.5);});
console.log(`\n${checks} test groups passed.`);
console.log('\nPrototype v0.3 baseline (balanced, no wall):');for(const [id,p]of Object.entries(PRESETS)){const b=new Battle({cards:p.cards});b.run();console.log(id,b.result,b.time.toFixed(2)+'s',b.units.map(u=>u.hp.toFixed(1)).join(' / '),'DoT',b.units[0].stats.dot.toFixed(1));}
