'use strict';
const assert=require('node:assert/strict');
const {STEP,MIN_GAP,CARDS,PRESETS,ENEMIES,makeCard,configFor,validate,clone,Battle,compare}=require('./link-engine.js');
let tests=0;
function test(name,fn){fn();tests++;console.log('PASS',name);}
function near(a,b){assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);}
function steps(b,n){for(let i=0;i<n;i++)b.step();}
function idle(){const c=configFor('plain');c.enemy='dummy';const b=new Battle(c);b.wands.forEach(w=>w.timer=999);return b;}
function hit(b,id,source=0,params={}){b.hit({source,c:makeCard(id,params)});b.drain();}
test('Defaults validate and character/wand data are separate',()=>{for(const p of Object.keys(PRESETS))assert.deepEqual(validate(configFor(p)),[]);const b=new Battle();assert.equal(b.wands.length,4);assert.equal(b.actors.length,2);assert.equal('hp' in b.wands[0],false);assert.equal('power' in b.wands[0],false);assert.equal('timer' in b.actors[0],false);});
test('Invalid cards, intervals, parameters and opponents rejected',()=>{for(const mutate of [c=>c.wands[0].cards=[],c=>c.wands[0].cards=[makeCard('relayRune')],c=>c.wands[0].cards=[{id:'unknown',params:{}}],c=>c.wands[0].interval=NaN,c=>c.wands[0].interval=.1,c=>c.wands[0].capacity=1.5,c=>c.wands[0].cards[0].params.damage=Infinity,c=>c.wands[0].cards[0].params.stacks=2.5,c=>c.enemy='missing',c=>c.hp=0]){const c=configFor();mutate(c);assert.ok(validate(c).length);assert.throws(()=>new Battle(c));}});
test('Capacity never silently deletes; total budget includes runes',()=>{const c=configFor();c.wands[0].capacity=2;assert.ok(validate(c).some(e=>e.includes('容量')));assert.equal(c.wands[0].cards.length,3);c.wands.forEach(w=>{w.capacity=5;w.cards=Array.from({length:5},()=>makeCard('spark'));});assert.ok(validate(c).some(e=>e.includes('8槽')));});
test('Per-instance edits do not leak to other cards or active battle',()=>{const c=configFor(),b=new Battle(c);c.wands[0].cards[0].params.damage=40;near(c.wands[0].cards[1].params.damage,4);near(b.wands[0].cards[0].params.damage,4);near(makeCard('ember').params.damage,4);});
test('Independent cadence; runes absent from active queue',()=>{const c=configFor();c.enemy='dummy';const b=new Battle(c);steps(b,54);assert.equal(b.wands[0].stats.casts,1);assert.equal(b.wands[1].stats.casts,0);assert.deepEqual(b.wands[0].active,[0,1]);assert.deepEqual(b.wands[1].active,[0]);assert.equal(b.wands[0].runes[0].count,1);});
test('Ready timers reset before cross-charge regardless of source position',()=>{for(const source of [0,1]){const c=configFor('plain');c.enemy='dummy';c.wands.forEach(w=>w.interval=1);c.wands[source].cards=[makeCard('charge')];const b=new Battle(c);steps(b,60);near(b.wands[1-source].timer,.6);assert.equal(b.wands[1-source].stats.casts,1);assert.equal(b.wands[source].stats.casts,1);}});
test('Recipient charged to zero only casts on next step',()=>{const c=configFor('plain');c.enemy='dummy';c.wands[0].cards=[makeCard('charge')];const b=new Battle(c);b.wands[0].timer=STEP;b.wands[1].timer=.1;b.step();assert.equal(b.wands[1].stats.casts,0);near(b.wands[1].timer,0);b.step();assert.equal(b.wands[1].stats.casts,1);});
test('Charge clamps excess and respects minimum post-cast gap',()=>{const b=idle(),[a,v]=b.wands;v.timer=1;v.lastAt=0;near(b.charge(a,v,9,'test'),.8);near(v.timer,.2);b.charge(a,v,9,'test');near(v.timer,.2);near(a.stats.charge,.8);b.time=.3;b.charge(a,v,9,'test');near(v.timer,0);assert.equal(v.stats.casts,0);});
test('Haste targets another friendly wand; refresh, coexistence and expiry',()=>{const b=idle(),[a,v]=b.wands;b.haste(a,v,3,'test');near(b.rate(a),1);near(b.rate(v),1.5);near(b.wands[2].hasteUntil,0);b.time=1;b.haste(a,v,3,'test');near(v.hasteUntil,4);near(b.rate(v),1.5);v.slowUntil=3;near(b.rate(v),1.05);b.time=3.1;near(b.rate(v),1.5);b.time=4.1;near(b.rate(v),1);});
test('Ice targets corresponding enemy wand only',()=>{const b=idle();hit(b,'ice',1);near(b.wands[3].slowUntil,2);near(b.wands[2].slowUntil,0);near(b.wands[1].slowUntil,0);});
test('Relay rune counts timed casts, not hits',()=>{const b=new Battle(),w=b.wands[0],r=w.runes[0];b.event('cast',w);b.drain();assert.equal(r.count,1);assert.equal(r.procs,0);hit(b,'ember');assert.equal(r.count,1);b.event('cast',w);b.drain();assert.equal(r.count,0);assert.equal(r.procs,1);});
test('Shared burn: A produces, B consumes and grants shield then charges A',()=>{const b=new Battle();hit(b,'ember',0);assert.equal(b.actors[1].burn,4);hit(b,'detonate',1);assert.equal(b.actors[1].burn,0);near(b.actors[0].shield,6);near(b.wands[0].timer,.7);assert.equal(b.wands[1].runes[0].procs,1);assert.equal(b.wands[1].runes[1].procs,1);});
test('Per-card consume cap and ratio; zero burn cannot trigger harvest',()=>{const b=new Battle();b.actors[1].burn=8;hit(b,'detonate',1,{consume:3,ratio:4,damage:2});assert.equal(b.actors[1].burn,5);near(b.actors[1].hp,286);const c=new Battle();hit(c,'detonate',1);near(c.actors[0].shield,0);assert.equal(c.wands[1].runes[0].procs,0);});
test('Full shield gives no event, partial shield only credits actual gain',()=>{const b=new Battle(),w=b.wands[1];b.actors[0].shield=80;near(b.shield(w,15,'test'),0);b.drain();assert.equal(w.runes[1].procs,0);b.actors[0].shield=78;near(b.shield(w,15,'test'),2);b.drain();assert.equal(w.runes[1].procs,1);near(b.actors[0].stats.shield,2);});
test('Conduit requires friendly shield and respects cooldown',()=>{const b=new Battle(),w=b.wands[1];b.shield(b.wands[2],10,'enemy');b.drain();assert.equal(w.runes[1].procs,0);b.shield(w,10,'self');b.drain();b.shield(w,10,'again');b.drain();assert.equal(w.runes[1].procs,1);b.time=1;b.shield(w,10,'later');b.drain();assert.equal(w.runes[1].procs,2);});
test('Toggle disables cross-wand effects but retains character effects',()=>{const c=configFor();c.links=false;const b=new Battle(c);hit(b,'ember');hit(b,'detonate',1);near(b.actors[0].shield,6);near(b.wands[0].timer,.9);assert.equal(b.links.length,0);b.haste(b.wands[0],b.wands[1],3,'test');near(b.wands[1].hasteUntil,0);});
test('Burn first tick, shield absorption, cap and no postponement',()=>{const b=idle(),a=b.actors[1];a.shield=50;hit(b,'ember');near(a.shield,46);steps(b,30);hit(b,'ember');near(a.burnAt,1);steps(b,30);near(a.shield,34);assert.equal(a.burn,7);b.addStatus(b.wands[0],a,'burn',100);assert.equal(a.burn,30);});
test('Poison pierces shield; shock consumed by later hits, not DoT',()=>{const b=idle(),a=b.actors[1];a.shield=50;hit(b,'venom');hit(b,'shock');near(a.shield,42);assert.equal(a.shock,2);steps(b,60);near(a.hp,798);assert.equal(a.poison,2);assert.equal(a.shock,2);hit(b,'spark');near(a.shield,24);assert.equal(a.shock,1);});
test('Projectile speed changes impact time, not cast count',()=>{const c=configFor('plain');c.enemy='dummy';c.wands[0].cards[0].params.speed=800;c.wands[1].cards[0].params.speed=180;const b=new Battle(c);b.cast(b.wands[0]);b.cast(b.wands[1]);b.wands.forEach(w=>w.timer=999);steps(b,60);assert.ok(b.wands[0].stats.damage>0);near(b.wands[1].stats.damage,0);assert.equal(b.wands[0].stats.casts,1);assert.equal(b.wands[1].stats.casts,1);});
test('Simultaneous lethal DoT draws; no overkill in statistics',()=>{const b=idle();for(const a of b.actors){a.hp=1;a.poison=5;a.poisonAt=1;}steps(b,60);assert.equal(b.result,'draw');near(b.actors[0].stats.damage,1);near(b.actors[1].stats.damage,1);});
test('No damage ends at 45s; invalid timestep rejected',()=>{const c=configFor('plain');c.enemy='dummy';c.wands.forEach(w=>w.cards=[makeCard('heal')]);const b=new Battle(c).run();assert.equal(b.result,'timeout');near(b.time,45);assert.throws(()=>b.step(.5));assert.throws(()=>b.step(NaN));});
test('Replay deterministic; compare does not mutate input',()=>{const c=configFor(),before=clone(c),a=new Battle(c).run(),b=new Battle(c).run();assert.deepEqual(a.summary(),b.summary());assert.deepEqual(a.logs,b.logs);const r=compare(c);assert.deepEqual(c,before);assert.ok(r.on.links>0);assert.equal(r.off.links,0);});
test('Mutual charge stress stays finite and respects 0.2s minimum',()=>{const c=configFor('plain');c.enemy='dummy';c.wands.forEach(w=>{w.interval=.4;w.capacity=4;w.cards=[makeCard('charge',{amount:1.2}),makeCard('relayRune',{every:1,amount:1,cooldown:.2}),makeCard('relayRune',{every:1,amount:1,cooldown:.2})];});const b=new Battle(c),previous=[-99,-99];while(!b.result){const counts=b.wands.slice(0,2).map(w=>w.stats.casts);b.step();b.wands.slice(0,2).forEach((w,i)=>{if(w.stats.casts>counts[i]){assert.ok(b.time-previous[i]>=MIN_GAP-1e-9);previous[i]=b.time;}});assert.equal(b.queue.length,0);}assert.equal(b.result,'timeout');for(const w of b.wands.slice(0,2))assert.ok(w.stats.casts<=225);});
test('All 24 preset/enemy/toggle combinations and all module types terminate',()=>{let count=0;for(const id of Object.keys(PRESETS))for(const enemy of Object.keys(ENEMIES))for(const links of [true,false]){const c=configFor(id);c.enemy=enemy;c.links=links;const b=new Battle(c).run();count++;assert.ok(b.result);for(const a of b.actors){assert.ok(a.hp>=0&&a.hp<=a.maxHp);assert.ok(a.shield>=0&&a.shield<=80);assert.ok(a.burn>=0&&a.burn<=30);assert.ok(a.stats.dot<=a.stats.damage);}assert.ok(b.projectiles.length<100);assert.equal(b.queue.length,0);}assert.equal(count,24);for(const [id,d]of Object.entries(CARDS)){const c=configFor('plain');c.enemy='dummy';c.wands[0].cards=d.kind==='spell'?[makeCard(id)]:[makeCard('ember'),makeCard(id)];assert.ok(new Battle(c).run().result);}});
console.log(`\n${tests} link-engine test groups passed.`);
console.log('Default comparison:',compare(configFor()));
